### ISSUE TITLE
Turn the search bar to an input field.

### ISSUE THREAD

**Issue by khaledkamr** [khaledkamr/FilmFan#1]
![Screenshot 2024-04-09 145844](https://github.com/khaledkamr/FilmFan/assets/94804298/7ccbeda4-c928-421c-bfb8-7f4105df55a1)

**the "What do you want to watch?" should be a placeholder not a value.**

**Comment by 01End** [comment]
Done, but :
- spaces is a little bugged 
-![Screenshot 2024-04-25 003429](https://github.com/khaledkamr/FilmFan/assets/146660003/9c1373ad-2de6-40e2-84be-44e5dc8ef229)
- The x button is to close
- 
![Screenshot 2024-04-25 003601](https://github.com/khaledkamr/FilmFan/assets/146660003/ac29f4ed-0a10-4aa3-8584-0ab9ea8b2918)
