### ISSUE TITLE
Activate the links of the Stars of the Movie

### ISSUE THREAD

**Issue by khaledkamr** [khaledkamr/FilmFan#3]
![Screenshot 2024-04-12 181438](https://github.com/khaledkamr/FilmFan/assets/94804298/960a7317-b0a1-42ab-a654-60350035ea47)
 
### **When the user click on the star name, the website should take him to the page of the star.**
**like this for example:**
#https://www.imdb.com/name/nm1500155/
![Screenshot 2024-04-12 181949](https://github.com/khaledkamr/FilmFan/assets/94804298/900abd14-ed84-428e-90ab-2eb35d0bece7)

**Comment by 01End** [comment]
Done, I linked all the (Director , Writers, Stars) with a link from IMDB
-
![Screenshot 2024-04-25 010731](https://github.com/khaledkamr/FilmFan/assets/146660003/2c066a61-a6b6-47f9-9f06-fbdc044d8b86)
